[versions]
kotlin = "2.1.0"
compose = "1.8.0"
agp = "8.8.2"
composetheme = "1.2.0-alpha"
composeicons = "1.0.0"

[libraries]
composetheme = { module = "com.composables:composetheme", version.ref = "composetheme" }
composeicons = { module = "com.composables:icons-lucide", version.ref = "composeicons" }


[plugins]
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
